[package]
name = "camrtsp-capture"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camrtsp-core.workspace = true
bytes.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
cidre = { version = "0.24.5", default-features = false, features = ["av", "vt", "dispatch", "macos_12_0"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Media_MediaFoundation",
  "Win32_Media_DirectShow",
  "Win32_System_Com",
  "Win32_System_Ole",
  "Win32_System_Variant",
] }
windows-core.workspace = true
